<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-I9ETKPH" failures="0" tests="1" name="automation.demo.tests.web.alza.shoppingcart.TC_01b" time="26.409" errors="1" timestamp="2022-07-12T09:56:54 SELÄŒ" skipped="0">
  <testcase classname="automation.demo.tests.web.alza.shoppingcart.TC_01b" name="test" time="26.409">
    <error message="There were some exceptions found during the test" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: There were some exceptions found during the test
at automation.demo.driver.driver.DriverManager.<init>(DriverManager.java:21)
at automation.demo.driver.driver.web.WebDriver.<init>(WebDriver.java:19)
at automation.demo.driver.driver.web.Chrome.<init>(Chrome.java:8)
at automation.demo.driver.Configuration$Browser$1.init(Configuration.java:66)
at automation.demo.driver.Configuration$Browser$1.init(Configuration.java:1)
at automation.demo.driver.driver.web.WebSession.initDriver(WebSession.java:8)
at automation.demo.WebTest.getWebDriver(WebTest.java:29)
at automation.demo.tests.web.alza.shoppingcart.TC_01b.test(TC_01b.java:17)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Suppressed: java.lang.RuntimeException: Shopping cart is not empty
at automation.demo.objects.web.alza.pages.ShoppingCartPage.assertEmptyShoppingCart(ShoppingCartPage.java:41)
at automation.demo.tests.web.alza.shoppingcart.TC_01b.test(TC_01b.java:35)
... 13 more
]]>
    </error>
  </testcase> <!-- test -->
  <system-out/>
</testsuite> <!-- automation.demo.tests.web.alza.shoppingcart.TC_01b -->
